### ISSUE TITLE
Pager should be at the bottom

### ISSUE THREAD

**Issue by ThomasKientz** [davideast/hnpwa-firebase#18]
Hi !

This is by far the best implementation of [HNPWA](https://hnpwa.com/) !! 

I would use every day, **but** the pager is currently at the bottom, so its stopped me of using it 😞 . So when we scroll down and arrive at end of the list, we have to scroll back up to reach the pager and load new content. Even if iOS have a shortcut to go back to the top of the page (by tapping the status bar), it's not convenient.

An infinite scrolling would be a better solution or put the pager at the bottom of the page and with an automatic scroll to top. 

What do you think ? Is it achievable in vanilla js ?

Thanks !

**Comment by davideast** [comment]
Hi @ThomasKientz!

Thank you so much for your kind words. I just accepted a PR that does just this. I'll do a deploy soon!

**Comment by ThomasKientz** [comment]
Still waiting :p

**Comment by pascaliske** [comment]
@ThomasKientz @davideast I just saw that I forgot to add the vendor prefix for the sticky positioning... I will prepare another PR for this now. 😄
